import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../features/settings/data/settings_providers.dart';

/// Supported locales for the app.
const List<Locale> supportedLocales = [
  Locale('en', 'US'),
  Locale('es', 'ES'),
  Locale('fr', 'FR'),
  Locale('de', 'DE'),
  Locale('pt', 'BR'),
  Locale('hi', 'IN'),
  Locale('ja', 'JP'),
  Locale('zh', 'CN'),
];

/// Human-readable language names keyed by locale code.
const Map<String, String> languageNames = {
  'en': 'ENGLISH',
  'es': 'ESPAÑOL',
  'fr': 'FRANÇAIS',
  'de': 'DEUTSCH',
  'pt': 'PORTUGUÊS',
  'hi': 'हिन्दी',
  'ja': '日本語',
  'zh': '中文',
};

/// Lightweight i18n service for the synthwave neon UI.
/// Returns TRANSLATED UPPERCASE STRINGS matching the app's aesthetic.
class AppLocalizations {
  final String _localeCode;

  AppLocalizations(this._localeCode);

  /// Look up a translation key.
  String t(String key) {
    final translations = _strings[_localeCode];
    if (translations != null && translations.containsKey(key)) {
      return translations[key]!;
    }
    // Fall back to English
    final enTranslations = _strings['en']!;
    return enTranslations[key] ?? key;
  }

  /// Convenience: format a string with a single replacement.
  String tF(String key, String arg) => t(key).replaceAll('{0}', arg);

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // ── Navigation ──
      'nav_home': 'HOME',
      'nav_budget': 'BUDGET',
      'nav_goals': 'GOALS',
      'nav_insights': 'INSIGHTS',
      'nav_education': 'DOJO',
      'nav_settings': 'CORE',

      // ── Settings sections ──
      'settings_title': 'CORE CONFIG',
      'section_identity': 'IDENTITY',
      'section_aesthetics': 'AESTHETICS',
      'section_modules': 'MODULES',
      'section_alerts': 'ALERTS',
      'section_data': 'DATA MANAGEMENT',
      'section_security': 'SECURITY',
      'section_open_source': 'OPEN_SOURCE',

      // ── Settings items ──
      'user_profile': 'USER PROFILE',
      'currency_protocol': 'CURRENCY PROTOCOL',
      'visual_interface': 'VISUAL INTERFACE',
      'crt_effect': 'CRT EFFECT',
      'crt_effect_sub': 'Scanlines & vignette overlay',
      'auto_theme': 'AUTO THEME SCHEDULE',
      'auto_theme_sub': 'Dark/light by time of day',
      'haptic_feedback': 'HAPTIC FEEDBACK',
      'haptic_feedback_sub': 'Vibration on actions & navigation',
      'sound_effects': 'SOUND EFFECTS',
      'sound_effects_sub': 'Synthwave system audio cues',
      'dark_start_time': 'DARK START TIME',
      'dark_start_time_sub': 'Auto-dark begins at',
      'dark_end_time': 'DARK END TIME',
      'dark_end_time_sub': 'Auto-dark ends at',
      'dark_mode_only': 'DARK MODE ONLY',
      'dark_mode_only_sub': 'Override: always use dark theme',
      'language': 'LANGUAGE',
      'language_sub': 'UI translation',
      'spending_categories': 'SPENDING CATEGORIES',
      'spending_categories_sub': 'CUSTOMIZE DATA MODULES',
      'chronos_module': 'CHRONOS MODULE',
      'chronos_module_sub': 'RECURRING TRANSACTIONS',
      'release_log': 'RELEASE LOG',
      'release_log_sub': 'VERSION HISTORY',
      'widget_tour': 'WIDGET TOUR',
      'widget_tour_sub': 'REPLAY ONBOARDING',
      'cloud_uplink': 'CLOUD UPLINK',
      'cloud_uplink_sub': 'ENCRYPTED SYNC',
      'export_archive': 'EXPORT ARCHIVE',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'CLEAR MAIN FRAME',
      'clear_data_sub': 'DESTRUCTIVE',
      'view_error': 'VIEW LAST ERROR',
      'biometric': 'BIOMETRIC FIREWALL',
      'projection_alerts': 'PROJECTION ALERTS',
      'projection_alerts_sub': 'AI collision detection',
      'daily_reminders': 'DAILY REMINDERS',
      'daily_reminders_sub': 'Log transaction prompts',
      'weekly_digest': 'WEEKLY DIGEST',
      'weekly_digest_sub': 'Sunday data summary',

      // ── Theme names ──
      'theme_synthwave84': 'SYNTHWAVE 84',
      'theme_synthwave': 'SYNTHWAVE',
      'theme_normal_dark': 'NORMAL DARK',
      'theme_normal_light': 'NORMAL LIGHT',

      // ── Budget page ──
      'budget_title': 'MAIN FRAME',
      'budget_empty': 'NO MEMORY MODULES DETECTED',
      'add_budget': 'INITIALIZE BUDGET',
      'spent_of': 'SPENT OF {0}',
      'system_health': 'SYSTEM HEALTH',
      'limit': 'LIMIT: {0}',
      'category_limit': 'CATEGORY LIMIT',
      'approaching_limit': 'APPROACHING LIMIT',
      'over_limit': 'OVER LIMIT',

      // ── Categories page ──
      'categories_title': 'MODULE LIBRARY',
      'new_category': 'INITIALIZE NEW MODULE',
      'edit_category': 'EDIT MODULE',
      'delete_category': 'TERMINATE MODULE?',
      'budget_limit': 'BUDGET LIMIT',
      'set_limit': 'SET LIMIT',
      'spent': 'SPENT: {0}',
      'remaining': 'REMAINING: {0}',

      // ── Generic ──
      'save': 'SAVE',
      'cancel': 'CANCEL',
      'commit': 'COMMIT',
      'close': 'CLOSE',
      'delete': 'DELETE',
      'confirm': 'CONFIRM',
      'amount': 'AMOUNT',
      'category': 'CATEGORY',
      'period': 'PERIOD',
      'name': 'NAME',
      'no_data': 'NO DATA',
      'active': 'ACTIVE',
      'inactive': 'INACTIVE',

      // ── Language picker ──
      'select_language': 'SELECT LANGUAGE',
    },
    'es': {
      // ── Navigation ──
      'nav_home': 'INICIO',
      'nav_budget': 'PRESUPUESTO',
      'nav_goals': 'METAS',
      'nav_insights': 'ANÁLISIS',
      'nav_education': 'DOJO',
      'nav_settings': 'NÚCLEO',

      // ── Settings sections ──
      'settings_title': 'CONFIG. NÚCLEO',
      'section_identity': 'IDENTIDAD',
      'section_aesthetics': 'ESTÉTICA',
      'section_modules': 'MÓDULOS',
      'section_alerts': 'ALERTAS',
      'section_data': 'GESTIÓN DATOS',
      'section_security': 'SEGURIDAD',
      'section_open_source': 'CÓDIGO ABIERTO',

      // ── Settings items ──
      'user_profile': 'PERFIL USUARIO',
      'currency_protocol': 'PROTOCOLO MONEDA',
      'visual_interface': 'INTERFAZ VISUAL',
      'crt_effect': 'EFECTO CRT',
      'crt_effect_sub': 'Líneas de escaneo y viñeta',
      'auto_theme': 'TEMA AUTOMÁTICO',
      'auto_theme_sub': 'Oscuro/claro según hora',
      'haptic_feedback': 'RETROALIMENTACIÓN HÁPTICA',
      'haptic_feedback_sub': 'Vibración en acciones y navegación',
      'sound_effects': 'EFECTOS DE SONIDO',
      'sound_effects_sub': 'Audio sintético del sistema',
      'dark_start_time': 'INICIO MODO OSCURO',
      'dark_start_time_sub': 'Oscuro comienza a las',
      'dark_end_time': 'FIN MODO OSCURO',
      'dark_end_time_sub': 'Oscuro termina a las',
      'dark_mode_only': 'SOLO MODO OSCURO',
      'dark_mode_only_sub': 'Anulación: siempre tema oscuro',
      'language': 'IDIOMA',
      'language_sub': 'Traducción de interfaz',
      'spending_categories': 'CATEGORÍAS GASTOS',
      'spending_categories_sub': 'PERSONALIZAR MÓDULOS',
      'chronos_module': 'MÓDULO CRONOS',
      'chronos_module_sub': 'TRANS. RECURRENTES',
      'release_log': 'REGISTRO VERSIONES',
      'release_log_sub': 'HISTORIAL',
      'widget_tour': 'TOUR GUIADO',
      'widget_tour_sub': 'REPRODUCIR INTRODUCCIÓN',
      'cloud_uplink': 'ENLACE NUBE',
      'cloud_uplink_sub': 'SINCRONIZACIÓN ENCRIPTADA',
      'export_archive': 'EXPORTAR ARCHIVO',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'BORRAR DATOS',
      'clear_data_sub': 'DESTRUCTIVO',
      'view_error': 'VER ÚLTIMO ERROR',
      'biometric': 'CORTABIEGO BIOMÉTRICO',
      'projection_alerts': 'ALERTAS PROYECCIÓN',
      'projection_alerts_sub': 'Detección de colisiones IA',
      'daily_reminders': 'RECORDATORIOS DIARIOS',
      'daily_reminders_sub': 'Avisos para registrar gastos',
      'weekly_digest': 'RESUMEN SEMANAL',
      'weekly_digest_sub': 'Resumen de datos domingo',

      // ── Theme names ──
      'theme_synthwave84': 'SINTÉTICA 84',
      'theme_synthwave': 'SINTÉTICA',
      'theme_normal_dark': 'NORMAL OSCURO',
      'theme_normal_light': 'NORMAL CLARO',

      // ── Budget page ──
      'budget_title': 'MARCO PRINCIPAL',
      'budget_empty': 'SIN MÓDULOS DETECTADOS',
      'add_budget': 'INICIALIZAR PRESUPUESTO',
      'spent_of': 'GASTADO DE {0}',
      'system_health': 'SALUD DEL SISTEMA',
      'limit': 'LÍMITE: {0}',
      'category_limit': 'LÍMITE CATEGORÍA',
      'approaching_limit': 'ACERCÁNDOSE AL LÍMITE',
      'over_limit': 'EXCEDE LÍMITE',

      // ── Categories page ──
      'categories_title': 'BIBLIOTECA MÓDULOS',
      'new_category': 'INICIALIZAR NUEVO MÓDULO',
      'edit_category': 'EDITAR MÓDULO',
      'delete_category': '¿TERMINAR MÓDULO?',
      'budget_limit': 'LÍMITE PRESUPUESTO',
      'set_limit': 'ESTABLECER LÍMITE',
      'spent': 'GASTADO: {0}',
      'remaining': 'RESTANTE: {0}',

      // ── Generic ──
      'save': 'GUARDAR',
      'cancel': 'CANCELAR',
      'commit': 'CONFIRMAR',
      'close': 'CERRAR',
      'delete': 'ELIMINAR',
      'confirm': 'CONFIRMAR',
      'amount': 'CANTIDAD',
      'category': 'CATEGORÍA',
      'period': 'PERÍODO',
      'name': 'NOMBRE',
      'no_data': 'SIN DATOS',
      'active': 'ACTIVO',
      'inactive': 'INACTIVO',

      // ── Language picker ──
      'select_language': 'SELECCIONAR IDIOMA',
    },
    'fr': {
      'nav_home': 'ACCUEIL',
      'nav_budget': 'BUDGET',
      'nav_goals': 'OBJECTIFS',
      'nav_insights': 'ANALYSES',
      'nav_education': 'DOJO',
      'nav_settings': 'NOYAU',
      'settings_title': 'CONFIG. NOYAU',
      'section_identity': 'IDENTITÉ',
      'section_aesthetics': 'ESTHÉTIQUE',
      'section_modules': 'MODULES',
      'section_alerts': 'ALERTES',
      'section_data': 'GESTION DONNÉES',
      'section_security': 'SÉCURITÉ',
      'section_open_source': 'CODE OUVERT',
      'user_profile': 'PROFIL UTILISATEUR',
      'currency_protocol': 'PROTOCOLE MONNAIE',
      'visual_interface': 'INTERFACE VISUELLE',
      'crt_effect': 'EFFET CRT',
      'crt_effect_sub': 'Lignes de balayage et vignette',
      'auto_theme': 'THÈME AUTO',
      'auto_theme_sub': 'Sombre/clair selon l\'heure',
      'haptic_feedback': 'RETOUR HAPTIQUE',
      'haptic_feedback_sub': 'Vibrations actions & navigation',
      'sound_effects': 'EFFETS SONORES',
      'sound_effects_sub': 'Signaux audio synthwave',
      'dark_start_time': 'DÉBUT SOMBRE',
      'dark_start_time_sub': 'Mode sombre commence à',
      'dark_end_time': 'FIN SOMBRE',
      'dark_end_time_sub': 'Mode sombre termine à',
      'dark_mode_only': 'SOMBRE SEULEMENT',
      'dark_mode_only_sub': 'Toujours thème sombre',
      'language': 'LANGUE',
      'language_sub': 'Traduction interface',
      'spending_categories': 'CATÉGORIES DÉPENSES',
      'spending_categories_sub': 'PERSONNALISER MODULES',
      'chronos_module': 'MODULE CHRONOS',
      'chronos_module_sub': 'TRANSACTIONS RÉCURRENTES',
      'release_log': 'JOURNAL VERSIONS',
      'release_log_sub': 'HISTORIQUE',
      'widget_tour': 'VISITE GUIDÉE',
      'widget_tour_sub': 'REJOUER INTRODUCTION',
      'cloud_uplink': 'LIAISON NUAGE',
      'cloud_uplink_sub': 'SYNCHRO CRYPTÉE',
      'export_archive': 'EXPORTER ARCHIVE',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'EFFACER DONNÉES',
      'clear_data_sub': 'DESTRUCTIF',
      'view_error': 'VOIR DERNIÈRE ERREUR',
      'biometric': 'PARE-FEU BIOMÉTRIQUE',
      'projection_alerts': 'ALERTES PROJECTION',
      'projection_alerts_sub': 'Détection collisions IA',
      'daily_reminders': 'RAPPELS QUOTIDIENS',
      'daily_reminders_sub': 'Invites de saisie',
      'weekly_digest': 'RÉSUMÉ HEBDOMADAIRE',
      'weekly_digest_sub': 'Récap données dimanche',
      'theme_synthwave84': 'SYNTHWAVE 84',
      'theme_synthwave': 'SYNTHWAVE',
      'theme_normal_dark': 'NORMAL SOMBRE',
      'theme_normal_light': 'NORMAL CLAIR',
      'budget_title': 'CADRE PRINCIPAL',
      'budget_empty': 'AUCUN MODULE DÉTECTÉ',
      'add_budget': 'INITIALISER BUDGET',
      'spent_of': 'DÉPENSÉ DE {0}',
      'system_health': 'SANTÉ SYSTÈME',
      'limit': 'LIMITE: {0}',
      'category_limit': 'LIMITE CATÉGORIE',
      'approaching_limit': 'LIMITE APPROCHANTE',
      'over_limit': 'DÉPASSE LIMITE',
      'categories_title': 'BIBLIOTHÈQUE MODULES',
      'new_category': 'NOUVEAU MODULE',
      'edit_category': 'MODIFIER MODULE',
      'delete_category': 'SUPPRIMER MODULE?',
      'budget_limit': 'LIMITE BUDGÉTAIRE',
      'set_limit': 'DÉFINIR LIMITE',
      'spent': 'DÉPENSÉ: {0}',
      'remaining': 'RESTANT: {0}',
      'save': 'SAUVER',
      'cancel': 'ANNULER',
      'commit': 'VALIDER',
      'close': 'FERMER',
      'delete': 'SUPPRIMER',
      'confirm': 'CONFIRMER',
      'amount': 'MONTANT',
      'category': 'CATÉGORIE',
      'period': 'PÉRIODE',
      'name': 'NOM',
      'no_data': 'AUCUNE DONNÉE',
      'active': 'ACTIF',
      'inactive': 'INACTIF',
      'select_language': 'CHOISIR LANGUE',
    },
    'de': {
      'nav_home': 'START',
      'nav_budget': 'BUDGET',
      'nav_goals': 'ZIELE',
      'nav_insights': 'EINBLICKE',
      'nav_education': 'DOJO',
      'nav_settings': 'KERN',
      'settings_title': 'KERNKONFIG',
      'section_identity': 'IDENTITÄT',
      'section_aesthetics': 'ÄSTHETIK',
      'section_modules': 'MODULE',
      'section_alerts': 'ALARME',
      'section_data': 'DATENVERWALTUNG',
      'section_security': 'SICHERHEIT',
      'section_open_source': 'OPEN SOURCE',
      'user_profile': 'BENUTZERPROFIL',
      'currency_protocol': 'WÄHRUNGSPROTOKOLL',
      'visual_interface': 'VISUELLE OBERFLÄCHE',
      'crt_effect': 'CRT-EFFEKT',
      'crt_effect_sub': 'Scanlinien & Vignette',
      'auto_theme': 'AUTO-THEMA',
      'auto_theme_sub': 'Dunkel/hell nach Uhrzeit',
      'haptic_feedback': 'HAKTISCHES FEEDBACK',
      'haptic_feedback_sub': 'Vibration bei Aktionen',
      'sound_effects': 'SOUNDEFFEKTE',
      'sound_effects_sub': 'Synthwave Systemaudio',
      'dark_start_time': 'DUNKELSTART',
      'dark_start_time_sub': 'Dunkelmodus beginnt um',
      'dark_end_time': 'DUNKELENDE',
      'dark_end_time_sub': 'Dunkelmodus endet um',
      'dark_mode_only': 'NUR DUNKEL',
      'dark_mode_only_sub': 'Immer dunkles Thema',
      'language': 'SPRACHE',
      'language_sub': 'UI-Übersetzung',
      'spending_categories': 'AUSGABENKATEGORIEN',
      'spending_categories_sub': 'MODULE ANPASSEN',
      'chronos_module': 'CHRONOS-MODUL',
      'chronos_module_sub': 'WIEDERK. BUCHUNGEN',
      'release_log': 'VERSIONEN',
      'release_log_sub': 'VERLAUF',
      'widget_tour': 'TOUR',
      'widget_tour_sub': 'EINFÜHRUNG WIEDERHOLEN',
      'cloud_uplink': 'CLOUD-UPLINK',
      'cloud_uplink_sub': 'VERSCHLÜSSELTE SYNC',
      'export_archive': 'ARCHIV EXPORTIEREN',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'DATEN LÖSCHEN',
      'clear_data_sub': 'ZERSTÖRERISCH',
      'view_error': 'LETZTEN FEHLER',
      'biometric': 'BIOMETRISCHE FIREWALL',
      'projection_alerts': 'PROJEKTIONSALARME',
      'projection_alerts_sub': 'KI-Kollision erkennen',
      'daily_reminders': 'TÄGLICHE ERINNERUNGEN',
      'daily_reminders_sub': 'Eingabeaufforderungen',
      'weekly_digest': 'WOCHENÜBERSICHT',
      'weekly_digest_sub': 'Sonntagsdaten',
      'theme_synthwave84': 'SYNTHWAVE 84',
      'theme_synthwave': 'SYNTHWAVE',
      'theme_normal_dark': 'NORMAL DUNKEL',
      'theme_normal_light': 'NORMAL HELL',
      'budget_title': 'HAUPTRAHMEN',
      'budget_empty': 'KEINE MODULE GEFUNDEN',
      'add_budget': 'BUDGET INITIALISIEREN',
      'spent_of': 'AUSGEGEBEN VON {0}',
      'system_health': 'SYSTEMGESUNDHEIT',
      'limit': 'GRENZE: {0}',
      'category_limit': 'KATEGORIEGRENZE',
      'approaching_limit': 'GRENZE NAHT',
      'over_limit': 'GRENZE ÜBERSCHRITTEN',
      'categories_title': 'MODULBIBLIOTHEK',
      'new_category': 'NEUES MODUL',
      'edit_category': 'MODUL BEARBEITEN',
      'delete_category': 'MODUL LÖSCHEN?',
      'budget_limit': 'BUDGETGRENZE',
      'set_limit': 'GRENZE SETZEN',
      'spent': 'AUSGEGEBEN: {0}',
      'remaining': 'ÜBRIG: {0}',
      'save': 'SPEICHERN',
      'cancel': 'ABBRECHEN',
      'commit': 'BESTÄTIGEN',
      'close': 'SCHLIESSEN',
      'delete': 'LÖSCHEN',
      'confirm': 'BESTÄTIGEN',
      'amount': 'BETRAG',
      'category': 'KATEGORIE',
      'period': 'ZEITRAUM',
      'name': 'NAME',
      'no_data': 'KEINE DATEN',
      'active': 'AKTIV',
      'inactive': 'INAKTIV',
      'select_language': 'SPRACHE WÄHLEN',
    },
    'pt': {
      'nav_home': 'INÍCIO',
      'nav_budget': 'ORÇAMENTO',
      'nav_goals': 'METAS',
      'nav_insights': 'ANÁLISES',
      'nav_education': 'DOJO',
      'nav_settings': 'NÚCLEO',
      'settings_title': 'CONFIG. NÚCLEO',
      'section_identity': 'IDENTIDADE',
      'section_aesthetics': 'ESTÉTICA',
      'section_modules': 'MÓDULOS',
      'section_alerts': 'ALERTAS',
      'section_data': 'GESTÃO DADOS',
      'section_security': 'SEGURANÇA',
      'section_open_source': 'CÓDIGO ABERTO',
      'user_profile': 'PERFIL USUÁRIO',
      'currency_protocol': 'PROTOCOLO MOEDA',
      'visual_interface': 'INTERFACE VISUAL',
      'crt_effect': 'EFEITO CRT',
      'crt_effect_sub': 'Linhas de varredura',
      'auto_theme': 'TEMA AUTOMÁTICO',
      'auto_theme_sub': 'Escuro/claro por horário',
      'haptic_feedback': 'FEEDBACK HÁPTICO',
      'haptic_feedback_sub': 'Vibração ações & navegação',
      'sound_effects': 'EFEITOS SONOROS',
      'sound_effects_sub': 'Áudio sintético synthwave',
      'dark_start_time': 'INÍCIO ESCURO',
      'dark_start_time_sub': 'Escuro começa às',
      'dark_end_time': 'FIM ESCURO',
      'dark_end_time_sub': 'Escuro termina às',
      'dark_mode_only': 'SÓ ESCURO',
      'dark_mode_only_sub': 'Sempre tema escuro',
      'language': 'IDIOMA',
      'language_sub': 'Tradução interface',
      'spending_categories': 'CATEGORIAS GASTOS',
      'spending_categories_sub': 'PERSONALIZAR MÓDULOS',
      'chronos_module': 'MÓDULO CRONOS',
      'chronos_module_sub': 'TRANS. RECORRENTES',
      'release_log': 'REGISTRO VERSÕES',
      'release_log_sub': 'HISTÓRICO',
      'widget_tour': 'TOUR GUIADO',
      'widget_tour_sub': 'REPRODUZIR INTRODUÇÃO',
      'cloud_uplink': 'LINK NUVEM',
      'cloud_uplink_sub': 'SINCRONIZAÇÃO CRIPTO',
      'export_archive': 'EXPORTAR ARQUIVO',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'LIMPAR DADOS',
      'clear_data_sub': 'DESTRUTIVO',
      'view_error': 'VER ÚLTIMO ERRO',
      'biometric': 'FIREWALL BIOMÉTRICO',
      'projection_alerts': 'ALERTAS PROJEÇÃO',
      'projection_alerts_sub': 'Detecção colisão IA',
      'daily_reminders': 'LEMBRETES DIÁRIOS',
      'daily_reminders_sub': 'Avisos registro',
      'weekly_digest': 'RESUMO SEMANAL',
      'weekly_digest_sub': 'Resumo dados domingo',
      'theme_synthwave84': 'SYNTHWAVE 84',
      'theme_synthwave': 'SYNTHWAVE',
      'theme_normal_dark': 'NORMAL ESCURO',
      'theme_normal_light': 'NORMAL CLARO',
      'budget_title': 'QUADRO PRINCIPAL',
      'budget_empty': 'SEM MÓDULOS DETECTADOS',
      'add_budget': 'INICIALIZAR ORÇAMENTO',
      'spent_of': 'GASTO DE {0}',
      'system_health': 'SAÚDE SISTEMA',
      'limit': 'LIMITE: {0}',
      'category_limit': 'LIMITE CATEGORIA',
      'approaching_limit': 'APROXIMANDO LIMITE',
      'over_limit': 'EXCEDEU LIMITE',
      'categories_title': 'BIBLIOTECA MÓDULOS',
      'new_category': 'NOVO MÓDULO',
      'edit_category': 'EDITAR MÓDULO',
      'delete_category': 'TERMINAR MÓDULO?',
      'budget_limit': 'LIMITE ORÇAMENTO',
      'set_limit': 'DEFINIR LIMITE',
      'spent': 'GASTO: {0}',
      'remaining': 'RESTANTE: {0}',
      'save': 'SALVAR',
      'cancel': 'CANCELAR',
      'commit': 'CONFIRMAR',
      'close': 'FECHAR',
      'delete': 'EXCLUIR',
      'confirm': 'CONFIRMAR',
      'amount': 'VALOR',
      'category': 'CATEGORIA',
      'period': 'PERÍODO',
      'name': 'NOME',
      'no_data': 'SEM DADOS',
      'active': 'ATIVO',
      'inactive': 'INATIVO',
      'select_language': 'SELECIONAR IDIOMA',
    },
    'hi': {
      'nav_home': 'होम',
      'nav_budget': 'बजट',
      'nav_goals': 'लक्ष्य',
      'nav_insights': 'अंतर्दृष्टि',
      'nav_education': 'डोजो',
      'nav_settings': 'कोर',
      'settings_title': 'कोर कॉन्फ़िग',
      'section_identity': 'पहचान',
      'section_aesthetics': 'सौंदर्यशास्त्र',
      'section_modules': 'मॉड्यूल',
      'section_alerts': 'अलर्ट',
      'section_data': 'डेटा प्रबंधन',
      'section_security': 'सुरक्षा',
      'section_open_source': 'ओपन सोर्स',
      'user_profile': 'उपयोगकर्ता प्रोफ़ाइल',
      'currency_protocol': 'मुद्रा प्रोटोकॉल',
      'visual_interface': 'दृश्य इंटरफ़ेस',
      'crt_effect': 'CRT प्रभाव',
      'crt_effect_sub': 'स्कैनलाइन और विग्नेट',
      'auto_theme': 'ऑटो थीम',
      'auto_theme_sub': 'समय के अनुसार डार्क/लाइट',
      'haptic_feedback': 'स्पर्श प्रतिक्रिया',
      'haptic_feedback_sub': 'कार्रवाई पर कंपन',
      'sound_effects': 'ध्वनि प्रभाव',
      'sound_effects_sub': 'सिंथवेव सिस्टम ऑडियो',
      'dark_start_time': 'डार्क प्रारंभ',
      'dark_start_time_sub': 'डार्क मोड शुरू',
      'dark_end_time': 'डार्क समाप्ति',
      'dark_end_time_sub': 'डार्क मोड समाप्त',
      'dark_mode_only': 'केवल डार्क',
      'dark_mode_only_sub': 'हमेशा डार्क थीम',
      'language': 'भाषा',
      'language_sub': 'UI अनुवाद',
      'spending_categories': 'खर्च श्रेणियाँ',
      'spending_categories_sub': 'मॉड्यूल अनुकूलित करें',
      'chronos_module': 'क्रोनोस मॉड्यूल',
      'chronos_module_sub': 'आवर्ती लेन-देन',
      'release_log': 'रिलीज़ लॉग',
      'release_log_sub': 'संस्करण इतिहास',
      'widget_tour': 'विजेट टूर',
      'widget_tour_sub': 'परिचय फिर से देखें',
      'cloud_uplink': 'क्लाउड अपलिंक',
      'cloud_uplink_sub': 'एन्क्रिप्टेड सिंक',
      'export_archive': 'संग्रह निर्यात',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'डेटा मिटाएँ',
      'clear_data_sub': 'विनाशकारी',
      'view_error': 'अंतिम त्रुटि देखें',
      'biometric': 'बायोमेट्रिक फ़ायरवॉल',
      'projection_alerts': 'प्रोजेक्शन अलर्ट',
      'projection_alerts_sub': 'AI टकराव पहचान',
      'daily_reminders': 'दैनिक अनुस्मारक',
      'daily_reminders_sub': 'लेन-देन संकेत',
      'weekly_digest': 'साप्ताहिक सारांश',
      'weekly_digest_sub': 'रविवार डेटा सारांश',
      'theme_synthwave84': 'सिंथवेव 84',
      'theme_synthwave': 'सिंथवेव',
      'theme_normal_dark': 'सामान्य डार्क',
      'theme_normal_light': 'सामान्य लाइट',
      'budget_title': 'मुख्य फ्रेम',
      'budget_empty': 'कोई मॉड्यूल नहीं',
      'add_budget': 'बजट आरंभ करें',
      'spent_of': '{0} में से खर्च',
      'system_health': 'सिस्टम स्वास्थ्य',
      'limit': 'सीमा: {0}',
      'category_limit': 'श्रेणी सीमा',
      'approaching_limit': 'सीमा के करीब',
      'over_limit': 'सीमा से अधिक',
      'categories_title': 'मॉड्यूल पुस्तकालय',
      'new_category': 'नया मॉड्यूल',
      'edit_category': 'मॉड्यूल संपादित करें',
      'delete_category': 'मॉड्यूल हटाएँ?',
      'budget_limit': 'बजट सीमा',
      'set_limit': 'सीमा सेट करें',
      'spent': 'खर्च: {0}',
      'remaining': 'शेष: {0}',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'commit': 'पुष्टि करें',
      'close': 'बंद करें',
      'delete': 'हटाएँ',
      'confirm': 'पुष्टि करें',
      'amount': 'राशि',
      'category': 'श्रेणी',
      'period': 'अवधि',
      'name': 'नाम',
      'no_data': 'कोई डेटा नहीं',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'select_language': 'भाषा चुनें',
    },
    'ja': {
      'nav_home': 'ホーム',
      'nav_budget': '予算',
      'nav_goals': '目標',
      'nav_insights': '分析',
      'nav_education': '道場',
      'nav_settings': 'コア',
      'settings_title': 'コア設定',
      'section_identity': 'アイデンティティ',
      'section_aesthetics': '美学',
      'section_modules': 'モジュール',
      'section_alerts': 'アラート',
      'section_data': 'データ管理',
      'section_security': 'セキュリティ',
      'section_open_source': 'オープンソース',
      'user_profile': 'ユーザープロフィール',
      'currency_protocol': '通貨プロトコル',
      'visual_interface': 'ビジュアルI/F',
      'crt_effect': 'CRT効果',
      'crt_effect_sub': 'スキャンラインとビネット',
      'auto_theme': '自動テーマ',
      'auto_theme_sub': '時刻でダーク/ライト切替',
      'haptic_feedback': '触覚フィードバック',
      'haptic_feedback_sub': '操作時に振動',
      'sound_effects': 'サウンド効果',
      'sound_effects_sub': 'シンセウェーブシステム音',
      'dark_start_time': 'ダーク開始',
      'dark_start_time_sub': 'ダークモード開始時刻',
      'dark_end_time': 'ダーク終了',
      'dark_end_time_sub': 'ダークモード終了時刻',
      'dark_mode_only': 'ダークのみ',
      'dark_mode_only_sub': '常にダークテーマ',
      'language': '言語',
      'language_sub': 'UI翻訳',
      'spending_categories': '支出カテゴリ',
      'spending_categories_sub': 'モジュールカスタマイズ',
      'chronos_module': 'クロノスモジュール',
      'chronos_module_sub': '定期取引',
      'release_log': 'リリースログ',
      'release_log_sub': 'バージョン履歴',
      'widget_tour': 'ガイドツアー',
      'widget_tour_sub': '紹介を再生',
      'cloud_uplink': 'クラウド接続',
      'cloud_uplink_sub': '暗号化同期',
      'export_archive': 'アーカイブ出力',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': 'データ消去',
      'clear_data_sub': '破壊的操作',
      'view_error': '最終エラー表示',
      'biometric': '生体認証ファイアウォール',
      'projection_alerts': '予測アラート',
      'projection_alerts_sub': 'AI衝突検出',
      'daily_reminders': '日次リマインダー',
      'daily_reminders_sub': '取引入力促進',
      'weekly_digest': '週次ダイジェスト',
      'weekly_digest_sub': '日曜データ要約',
      'theme_synthwave84': 'シンセウェーブ84',
      'theme_synthwave': 'シンセウェーブ',
      'theme_normal_dark': 'ノーマルダーク',
      'theme_normal_light': 'ノーマルライト',
      'budget_title': 'メインフレーム',
      'budget_empty': 'モジュール未検出',
      'add_budget': '予算初期化',
      'spent_of': '{0}中使用済',
      'system_health': 'システム健全性',
      'limit': '制限: {0}',
      'category_limit': 'カテゴリ制限',
      'approaching_limit': '制限間近',
      'over_limit': '制限超過',
      'categories_title': 'モジュールライブラリ',
      'new_category': '新規モジュール',
      'edit_category': 'モジュール編集',
      'delete_category': 'モジュール削除?',
      'budget_limit': '予算制限',
      'set_limit': '制限設定',
      'spent': '支出: {0}',
      'remaining': '残り: {0}',
      'save': '保存',
      'cancel': 'キャンセル',
      'commit': '確定',
      'close': '閉じる',
      'delete': '削除',
      'confirm': '確認',
      'amount': '金額',
      'category': 'カテゴリ',
      'period': '期間',
      'name': '名前',
      'no_data': 'データなし',
      'active': 'アクティブ',
      'inactive': '非アクティブ',
      'select_language': '言語選択',
    },
    'zh': {
      'nav_home': '首页',
      'nav_budget': '预算',
      'nav_goals': '目标',
      'nav_insights': '洞察',
      'nav_education': '道场',
      'nav_settings': '核心',
      'settings_title': '核心配置',
      'section_identity': '身份',
      'section_aesthetics': '美学',
      'section_modules': '模块',
      'section_alerts': '警报',
      'section_data': '数据管理',
      'section_security': '安全',
      'section_open_source': '开源',
      'user_profile': '用户资料',
      'currency_protocol': '货币协议',
      'visual_interface': '视觉界面',
      'crt_effect': 'CRT效果',
      'crt_effect_sub': '扫描线和暗角',
      'auto_theme': '自动主题',
      'auto_theme_sub': '按时间切换深色/浅色',
      'haptic_feedback': '触觉反馈',
      'haptic_feedback_sub': '操作及导航震动',
      'sound_effects': '音效',
      'sound_effects_sub': '合成波系统音效',
      'dark_start_time': '深色开始',
      'dark_start_time_sub': '深色模式开始于',
      'dark_end_time': '深色结束',
      'dark_end_time_sub': '深色模式结束于',
      'dark_mode_only': '仅深色',
      'dark_mode_only_sub': '始终使用深色主题',
      'language': '语言',
      'language_sub': '界面翻译',
      'spending_categories': '支出分类',
      'spending_categories_sub': '自定义模块',
      'chronos_module': '时间模块',
      'chronos_module_sub': '定期交易',
      'release_log': '发布日志',
      'release_log_sub': '版本历史',
      'widget_tour': '引导游览',
      'widget_tour_sub': '重播介绍',
      'cloud_uplink': '云连接',
      'cloud_uplink_sub': '加密同步',
      'export_archive': '导出归档',
      'export_archive_sub': 'JSON / CSV',
      'clear_data': '清除数据',
      'clear_data_sub': '破坏性操作',
      'view_error': '查看最后错误',
      'biometric': '生物识别防火墙',
      'projection_alerts': '预测警报',
      'projection_alerts_sub': 'AI碰撞检测',
      'daily_reminders': '每日提醒',
      'daily_reminders_sub': '交易录入提示',
      'weekly_digest': '每周摘要',
      'weekly_digest_sub': '周日数据总结',
      'theme_synthwave84': '合成波84',
      'theme_synthwave': '合成波',
      'theme_normal_dark': '普通深色',
      'theme_normal_light': '普通浅色',
      'budget_title': '主框架',
      'budget_empty': '未检测到模块',
      'add_budget': '初始化预算',
      'spent_of': '{0}中已花费',
      'system_health': '系统健康',
      'limit': '限额: {0}',
      'category_limit': '分类限额',
      'approaching_limit': '接近限额',
      'over_limit': '超过限额',
      'categories_title': '模块库',
      'new_category': '新建模块',
      'edit_category': '编辑模块',
      'delete_category': '删除模块?',
      'budget_limit': '预算限额',
      'set_limit': '设置限额',
      'spent': '已花费: {0}',
      'remaining': '剩余: {0}',
      'save': '保存',
      'cancel': '取消',
      'commit': '确认',
      'close': '关闭',
      'delete': '删除',
      'confirm': '确认',
      'amount': '金额',
      'category': '分类',
      'period': '周期',
      'name': '名称',
      'no_data': '无数据',
      'active': '活跃',
      'inactive': '非活跃',
      'select_language': '选择语言',
    },
  };
}

/// Provider that serves AppLocalizations based on the user's language setting.
final localeProvider = Provider<AppLocalizations>((ref) {
  final settings = ref.watch(settingsProvider);
  return AppLocalizations(settings.language);
});

/// Provider for the current Locale object (used by MaterialApp).
final currentLocaleProvider = Provider<Locale>((ref) {
  final settings = ref.watch(settingsProvider);
  return Locale(settings.language);
});
